const orders = [
    { srNo: 1, orderedBy: "Amit Sharma", menu: "Chole Bhature", quantity: 2, totalPrice: 500, rating: 4.5},
    { srNo: 2, orderedBy: "Priya Desai", menu: "Veg Biryani", quantity: 1, totalPrice: 250, rating: 4.2, comment: "Aromatic and flavorful." },
    { srNo: 3, orderedBy: "Rohan Mehta", menu: "Chicken Curry", quantity: 1, totalPrice: 300, rating: 4.8, comment: "Great taste and quantity!" },
    { srNo: 4, orderedBy: "Neha Kapoor", menu: "Chole Bhature", quantity: 1, totalPrice: 100, rating: 4.0, comment: "Simple and tasty." },
    { srNo: 5, orderedBy: "Vikram Rao", menu: "Chole Bhature", quantity: 1, totalPrice: 180, rating: 4.7, comment: "Crispy and delicious!" },
    { srNo: 6, orderedBy: "Anjali Verma", menu: "Chole Bhature", quantity: 1, totalPrice: 350, rating: 4.3, comment: "Perfectly cooked paneer." },
    { srNo: 7, orderedBy: "Siddharth Patel", menu: "Chicken Curry", quantity: 1, totalPrice: 600, rating: 4.9, comment: "Juicy and smoky flavor!" },
    { srNo: 8, orderedBy: "Kavita Singh", menu: "Rajma Chawal", quantity: 1, totalPrice: 220, rating: 4.1, comment: "Authentic taste!" },
    { srNo: 9, orderedBy: "Rahul Nair", menu: "Fish Curry", quantity: 1, totalPrice: 350, rating: 4.6, comment: "Fresh and tasty." },
    { srNo: 10, orderedBy: "Meera Joshi", menu: "Aloo Paratha", quantity: 2, totalPrice: 160, rating: 4.2, comment: "Crispy and flavorful!" },
    { srNo: 11, orderedBy: "Rajat Malhotra", menu: "Palak Paneer", quantity: 1, totalPrice: 330, rating: 4.4, comment: "Healthy and tasty!" },
    { srNo: 12, orderedBy: "Sonali Deshpande", menu: "Misal Pav", quantity: 1, totalPrice: 140, rating: 4.0, comment: "Spicy and authentic!" },
    { srNo: 13, orderedBy: "Abhishek Yadav", menu: "Chicken Curry", quantity: 1, totalPrice: 480, rating: 4.9, comment: "Rich and delicious." },
    { srNo: 14, orderedBy: "Pooja Saxena", menu: "Dosa", quantity: 1, totalPrice: 200, rating: 4.3, comment: "Crispy and well-made!" },
    { srNo: 15, orderedBy: "Aakash Trivedi", menu: "Pav Bhaji", quantity: 6, totalPrice: 180, rating: 4.7, comment: "Soft and juicy!" },
    { srNo: 16, orderedBy: "Sneha Agarwal", menu: "Paneer Tikka", quantity: 1, totalPrice: 280, rating: 4.6, comment: "Tasty and well-spiced." },
    { srNo: 17, orderedBy: "Kunal Jha", menu: "Biryani", quantity: 1, totalPrice: 300, rating: 4.8, comment: "Authentic Hyderabadi taste!" },
    { srNo: 18, orderedBy: "Tanya Rao", menu: "Pav Bhaji", quantity: 1, totalPrice: 220, rating: 4.1, comment: "Perfectly cooked noodles." },
    { srNo: 19, orderedBy: "Harsh Vardhan", menu: "Pav Bhaji", quantity: 1, totalPrice: 320, rating: 4.5, comment: "Rich and creamy!" },
    { srNo: 20, orderedBy: "Divya Menon", menu: "Idli", quantity: 2, totalPrice: 180, rating: 4.2, comment: "Soft and fresh!" },
    { srNo: 21, orderedBy: "Aditya Kumar", menu: "Gobi Manchurian", quantity: 1, totalPrice: 260, rating: 4.6, comment: "Crispy and delicious!" },
    { srNo: 22, orderedBy: "Rashmi Tiwari", menu: "Chole Bhature", quantity: 1, totalPrice: 250, rating: 4.3, comment: "Creamy and cheesy!" },
    { srNo: 23, orderedBy: "Sandeep Das", menu: "Chicken Curry", quantity: 1, totalPrice: 290, rating: 4.4, comment: "Perfectly spiced!" },
    { srNo: 24, orderedBy: "Nikita Paul", menu: "Chicken Curry", quantity: 1, totalPrice: 190, rating: 4.5, comment: "Refreshing and sweet." },
    { srNo: 25, orderedBy: "Manoj Mishra", menu: "Chicken Curry", quantity: 1, totalPrice: 450, rating: 4.8, comment: "Excellent flavors!" },
    { srNo: 26, orderedBy: "Swati Narayan", menu: "Pav Bhaji", quantity: 1, totalPrice: 200, rating: 4.3, comment: "Perfect street-style taste!" },
    { srNo: 27, orderedBy: "Vivek Anand", menu: "Chicken Curry", quantity: 1, totalPrice: 350, rating: 4.7, comment: "Complete and delicious!" },
    { srNo: 28, orderedBy: "Shruti Bajpai", menu: "Chicken Curry", quantity: 1, totalPrice: 230, rating: 4.1, comment: "Good balance of flavors." },
    { srNo: 29, orderedBy: "Ramesh Iyer", menu: "Dhokla", quantity: 1, totalPrice: 150, rating: 4.2, comment: "Soft and spongy!" },
    { srNo: 30, orderedBy: "Rekha Sharma", menu: "Chicken Curry", quantity: 1, totalPrice: 300, rating: 4.5, comment: "Tangy and crunchy!" }
  ];

  export default orders;