# Generated by Django 4.1 on 2025-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('#00', 'User'), ('#01', 'Mess Owner'), ('#02', 'Admin')], max_length=50)),
            ],
        ),
    ]
