# Generated by Django 4.1 on 2025-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.CharField(max_length=50, unique=True)),
                ('imgs', models.IntegerField()),
                ('open_time', models.CharField(max_length=100)),
                ('mess_name', models.CharField(max_length=100)),
                ('mess_address', models.TextField()),
                ('crowd_status', models.IntegerField(default=-1)),
                ('mess_rating', models.FloatField()),
                ('geo_lat', models.FloatField()),
                ('geo_lng', models.FloatField()),
                ('keywords', models.JSONField()),
            ],
        ),
    ]
