# Generated by Django 4.1 on 2025-03-11 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('menu', models.JSONField()),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PARTNER.messinfo')),
            ],
        ),
    ]
