# Generated by Django 4.1 on 2025-03-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0002_menuinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinfo',
            name='mess',
            field=models.ForeignKey(db_column='mess_id', on_delete=django.db.models.deletion.CASCADE, to='PARTNER.messinfo', to_field='mess_id'),
        ),
    ]
