# Generated by Django 4.1 on 2025-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0004_orderinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='order_id',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
