# Generated by Django 4.1 on 2025-03-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0005_orderinformation_order_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messinfo',
            table='PARTNER_messinfo',
        ),
    ]
