# Generated by Django 4.1 on 2025-03-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0006_alter_messinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messinfo',
            table='partner_messinfo',
        ),
    ]
