# Generated by Django 4.1 on 2025-03-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0007_alter_messinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menuinfo',
            table='partner_menuinfo',
        ),
        migrations.AlterModelTable(
            name='orderinformation',
            table='partner_orderinformation',
        ),
    ]
