# Generated by Django 4.1 on 2025-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0008_alter_menuinfo_table_alter_orderinformation_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'partner_partnerinfo',
            },
        ),
    ]
