# Generated by Django 5.1.7 on 2025-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0009_partnerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='order_status',
            field=models.CharField(choices=[('pending', -1), ('confirmed', 0), ('preparing', 1), ('delivered', 2)], default=-1, max_length=100),
        ),
    ]
