# Generated by Django 5.1.7 on 2025-04-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PARTNER', '0010_orderinformation_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messinfo',
            name='is_accepting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderinformation',
            name='order_status',
            field=models.CharField(choices=[('pending', -1), ('confirmed', 0), ('delivered', 1)], default=-1, max_length=100),
        ),
    ]
